### ISSUE TITLE
Column 'type' Conflict in 'Transaction' and 'Category'

### ISSUE THREAD

**Issue by imamhidayat92** [imamhidayat92/aturdoku-web#12]
Need to modify `Transaction` and `Category` table schema. Because implement this model relationship will crashing the apps:

``` php
class Transaction extends AppModel {
    // ...
    public $hasOne = array('Category');
}
```

**Comment by andhinisaras** [comment]
mam, yg ini uda bener belom sih?

**Comment by imamhidayat92** [comment]
Yap, fixed. Thank you Ras. :+1:
